name: 🚀 Release and Publish

on:
  push:
    branches: [main]

jobs:
  test:
    name: ✅ Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          TEST_ID_1: ${{ secrets.TEST_ID_1 }}

  release:
    name: 📦 Publish to npm & GitHub
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Get package version
        id: version
        shell: bash
        run: |
          VERSION=$(npm pkg get version | tr -d '"')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create tarball
        run: npm pack
        id: pack

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          body: |
            Release of version v${{ steps.version.outputs.version }}.
          files: |
            *.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
